C="javac"

all: SalesCommissions VariableLength InitArray

SalesCommissions: SalesCommissions.java
	$(C) SalesCommissions.java		

VariableLength: VariableLength.java
	$(C) VariableLength.java

InitArray: InitArray.java
	$(C) InitArray.java

clean:
	rm *.class
