C="javac"

all: SalesCommissions VariableLength InitArray Array2D SumOf

SalesCommissions: SalesCommissions.java
	$(C) SalesCommissions.java		

VariableLength: VariableLength.java
	$(C) VariableLength.java

InitArray: InitArray.java
	$(C) InitArray.java

SumOf: SumOf.java
	$(C) SumOf.java

Array2D: Array2D.java
	$(C) Array2D.java

clean:
	rm *.class
