C="javac"

all: SalesCommisions VariableLength GuessTheNumber

SalesCommisions: SalesCommisions.java
	$(C) SalesCommisions.java		

VariableLength: VariableLength.java
	$(C) VariableLength.java

GuessTheNumber: GuessTheNumber.java
	$(C) GuessTheNumber.java

clean:
	rm *.class
