C="javac"

all: BonusTest.java Dependencies
	$(C) BonusTest.java

Dependencies: Employee.java Date.java HourlyEmployee.java CommissionEmployee.java SalariedEmployee.java BasePlusCommissionEmployee.java

clean:
	rm *.class
