C="javac"

all: Round CoinFlip GuessTheNumber

Round: Round.java
	$(C) Round.java		

CoinFlip: CoinFlip.java
	$(C) CoinFlip.java

GuessTheNumber: GuessTheNumber.java
	$(C) GuessTheNumber.java

clean:
	rm *.class
