C="javac"

all: CommissionEmployeeTest BasePlusCommissionEmployeeTest HourlyEmployeeTest

CommissionEmployeeTest: CommissionEmployeeTest.java
	$(C) CommissionEmployeeTest.java

BasePlusCommissionEmployeeTest: BasePlusCommissionEmployeeTest.java
	$(C) BasePlusCommissionEmployeeTest.java

HourlyEmployeeTest: HourlyEmployeeTest.java
	$(C) HourlyEmployeeTest.java

clean:
	rm *.class
