C="javac"

all: Time2Test TickTest DateTest DateAndTimeTest

Time2Test: Time2Test.java
	$(C) Time2Test.java		

TickTest: TickTest.java
	$(C) TickTest.java

DateTest: DateTest.java
	$(C) DateTest.java

DateAndTimeTest: DateAndTimeTest.java
	$(C) DateAndTimeTest.java

##Array2D: Array2D.java
##	$(C) Array2D.java
##
clean:
	rm *.class
